services:
  demo-ecs:
    build:
      context: .
      target: prod
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws
    profiles: [app]

  demo-ecs-test:
    build:
      context: .
      target: test
    profiles: [test]
