name: Build + Deploy Container

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Test build
        env:
          REGISTRY: test
          REPOSITORY: ecs-demo
          IMAGE_TAG: ${{ steps.package-version.outputs.current-version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAGG --progress=plain --no-cache --target=test ./app

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ecs-demo
          IMAGE_TAG: ${{ steps.package-version.outputs.current-version }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --target=prod ./app
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
